version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels:
      - "dependencies"
      - "bot"

  - package-ecosystem: maven
    directory: /
    schedule:
      interval: daily
    labels:
      - "dependencies"
      - "bot"
