name: Release
description: Propose a new major/minor/milestone release
title: "[Release]: "
labels: ["release"] #Verified - label exists
body:
  - type: markdown
    attributes: 
      value: |
        This issue is to help the committers to the Jakarta Concurrency project to propose
        and complete the release process.
  - type: textarea
    attributes:
      label: Proposal
      description: |
        Why is a release needed?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Outstanding work
      description: |
        Issues / pulls to finish before this release can become generally available.
      value: |
        - [ ] 
    validations:
      required: false
  - type: textarea
    attributes:
      label: Check List
      description: |
        This is a checklist of what needs to be completed during the release process.
        This checklist typically does not need to be edited prior to submitting this form.
      value: |
          #### Prepare
            - [X] Open this issue.
            - [ ] Complete outstanding work
            - [ ] [Update TCK Signatures to capture API changes](https://github.com/jakartaee/concurrency/actions/workflows/update.yml)
          #### Stage release
            - [ ] [Build and stage artifacts to staging repository](https://ci.eclipse.org/cu/view/Release%20Builds/job/concurrency_api_1-build-and-stage/)
            - [ ] [Build and stage the TCK distribution artifact to download.eclipse.org](https://ci.eclipse.org/cu/view/Eclipse%20Builds/job/concurrency_tck_1-pull-and-stage/)
            - [ ] Update this issue with a comment that links to the staged artifacts and the generated GitHub branch and tag
            - [ ] [Create a `draft` on GitHub](https://github.com/jakartaee/concurrency/releases/new)
          #### Verify and modify
            - [ ] Ask for feedback from the community to verify the staged artifact has all the expected changes.
            - [ ] If anything needs to be added before publishing do that now and repeat the `Stage Release` section
          #### Publish release
            - [ ] [Publish staged artifacts to the public repository](https://ci.eclipse.org/cu/view/Release%20Builds/job/concurrency_api_3-staging-to-release/)
            - [ ] [Publish staged TCK distribution artifact to download.eclipse.org](https://ci.eclipse.org/cu/view/Eclipse%20Builds/job/concurrency_tck_2-staging-to-promoted/)
            - [ ] Update this issue with a comment that links to the published artifacts and the generated GitHub branch and tag
            - [ ] [Modify the `draft` release on GitHub to be `latest` or `pre-release`](https://github.com/jakartaee/concurrency/releases)
          #### Follow up
            - [ ] [Email the Concurrency Mailing list to have a Jakarta Steering Committee member promote the TCK Distribution publically](https://accounts.eclipse.org/mailing-list/cu-dev)
              - via [Jenkins build](https://ci.eclipse.org/jakartaee-spec-committee/job/promote-release/)
            - [ ] [Create pull request to https://github.com/jakartaee/specifications](https://github.com/jakartaee/specifications/blob/master/.github/PULL_REQUEST_TEMPLATE/pull_request_template.md)
              - upload [generated specification documentation](https://github.com/jakartaee/concurrency/actions/workflows/specification.yml)
            - [ ] Update versions in non-build files, such as:
              Documentation:
              - [tck/README.adoc](https://github.com/jakartaee/concurrency/tree/main/tck#getting-the-tck)
              - [concurrency-tck-reference-guide.adoc](https://github.com/jakartaee/concurrency/blob/main/tck-dist/src/main/asciidoc/concurrency-tck-reference-guide.adoc)
    validations:
      required: true