# This workflow will run when a release is created, and automatically update GitHub issue templates

name: GitHub Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - name: Create branch
      run: git checkout -b update-templates-${{ github.sha }}
    - name: Insert release - ${{ github.event.release.tag_name }}
      uses: mikefarah/yq@5f4c1fbd0ab1f7c1c97c23deb355a9a4d5077f66 #v4.40.1
      with:
        cmd: |
            yq -i '( .body.[] | select(.id == "version") ) ref $x | $x .attributes.options = ["${{ github.event.release.tag_name }}"] + $x .attributes.options' .github/ISSUE_TEMPLATE/bug-report.yml &&
            yq -i '( .body.[] | select(.id == "version") ) ref $x | $x .attributes.options = ["${{ github.event.release.tag_name }}"] + $x .attributes.options' .github/ISSUE_TEMPLATE/tck-challenge.yml
    - name: Needs updates
      id: update
      run: |
        echo "update_count=$(git status -s -uno | wc -l)" >> $GITHUB_OUTPUT
        echo "update_files=$(git status -s -uno)"         >> $GITHUB_OUTPUT
    - name: Create Pull Request
      if: steps.update.outputs.update_count > 0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"

        git add .github/ISSUE_TEMPLATE/bug-report.yml
        git add .github/ISSUE_TEMPLATE/tck-challenge.yml

        git commit -m "Update templates to include release ${{ github.event.release.tag_name }}"
        git push origin update-templates-${{ github.sha }}

        gh pr create \
          -B main \
          --title 'Update templates to include release ${{ github.event.release.tag_name }}' \
          --body '${{ steps.update.outputs.update_files }}' \
          --label 'version' \
          --label 'bot'
