# This workflow automates the creation of Specification Documents
# which will be copied into https://github.com/jakartaee/specifications

name: Generate specification documentation

on: 
    workflow_dispatch:
        inputs:
            specVersion:
                description: 'Major and Minor level of release. Example: 3.1'
                required: true

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Set up JDK 21
      uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4.5.0
      with:
        java-version: 21
        distribution: 'temurin'
        cache: maven
    - name: Generate specification docs
      #TODO remove -Pstaging once all Jakarta EE 11 dependencies are GA
      run: |
        mvn package -Pstaging --file api/pom.xml -Dspec.version=${{ github.event.inputs.specVersion }}
        mvn package -Pstaging --file specification/pom.xml -Dstatus=FINAL -Dspec.version=${{ github.event.inputs.specVersion }}
    - name: Assemble documentation
      run: |
        mkdir documentation/
        cp specification/target/generated-docs/jakarta-concurrency-spec-${{ github.event.inputs.specVersion }}.pdf   documentation/jakarta-concurrency-spec-${{ github.event.inputs.specVersion }}.pdf
        cp specification/target/generated-docs/jakarta-concurrency-spec-${{ github.event.inputs.specVersion }}.html  documentation/jakarta-concurrency-spec-${{ github.event.inputs.specVersion }}.html
        cp -r api/target/apidocs/ documentation/apidocs
    - name: Upload documentation
      uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
      with:
        name: Specification Documentation
        path: documentation/
        if-no-files-found: error
